### ISSUE TITLE
Cannot exclude files / folder

### ISSUE THREAD

**Issue by Wzb3422** [fangbinwei/aliyun-oss-website-action#2]
In my project, webpack bundles are created along with a json file (stats.json 24MB). The json file should not be uploaded.

But there is no configuration property to set files to exclude.

**Comment by fangbinwei** [comment]
maybe workaround:

```yml
- name: Clean files before upload
  run: rm -f dist/stats.json
```

**Comment by fangbinwei** [comment]
support [`exclude`](https://github.com/fangbinwei/aliyun-oss-website-action#exclude) now.

Thanks for your suggestion.
