### ISSUE TITLE
[docs] 阿里云OSS的CDN缓存自动刷新功能

### ISSUE THREAD

**Issue by lzimd** [fangbinwei/aliyun-oss-website-action#3]
补充一个场景文档。

阿里云 OSS 有个功能「CDN 缓存自动刷新」，支持针对指定操作触发。

如果使用阿里云的CDN并绑定加速域名回源到OSS，就可以使用OSS的CDN缓存自动刷新功能，此功能在**覆盖写**的情况下（包括覆盖一个已有的文件，删除一个已有的文件），OSS会主动刷新CDN，回源到OSS获取覆盖后的文件，不需要显式调用CDN的刷新接口。

所以，当触发操作仅配置为「PutObject」时，先删除再上传的方式并不会触发刷新，可以将「DeleteObject」也配置为触发操作。

**Comment by fangbinwei** [comment]
> 当触发操作仅配置为「PutObject」时，先删除再上传的方式并不会触发刷新，可以将「DeleteObject」也配置为触发操作

非常感谢, 测试了下, 似乎确实如此, 已经补充了README. 或许先覆盖上传, 再删掉多余的文件会合理一点.

**Comment by narumi147** [comment]
请问一下覆盖上传前是否有对hash做对比？如果文件内容没有变化，覆盖上传会发生不必要的CDN刷新？
