### ISSUE TITLE
请教个问题，我每次上传到oss 里面总是会有一个默认的dist 文件夹

### ISSUE THREAD

**Issue by zuo305** [fangbinwei/aliyun-oss-website-action#4]
请教个问题，我每次上传到oss 里面总是会有一个默认的dist 文件夹，但是我希望，直接上传文件本身，而不用带这个dist 文件夹可以吗？我build完之后是会有一个dist文件夹的，但是我希望上传时，直接上传dist里面的文件，而不是dist 本身，尝试了好多方法都不行，特来求教。

**Comment by fangbinwei** [comment]
例如我的项目构建target目录为`.vuepress/dist`, 配置`folder: .vuepress/dist`. 你那是什么情况呢

**Comment by zuo305** [comment]
> 例如我的项目构建target目录为`.vuepress/dist`, 配置`folder: .vuepress/dist`. 你那是什么情况呢

哦，感谢回答，不好意思，我现在可以了，我发现如果我写成  folder: ./dist 就会默认多一个dist 文件夹，但是如果我直接用 dist 就可以。

**Comment by fangbinwei** [comment]
>如果我写成 folder: ./dist 就会默认多一个dist 文件夹

我排查一下

**Comment by fangbinwei** [comment]
已经发布了新的版本修复了这个问题,  如果action配置里使用的tag v1, 那就能直接生效. 感谢

**Comment by zuo305** [comment]
> 已经发布了新的版本修复了这个问题, 如果action配置里使用的tag v1, 那就能直接生效. 感谢

嗯，测试过了，已经可以了，感谢。
