### ISSUE TITLE
大佬帮忙看一下，删除步骤一直报错返回400状态码

### ISSUE THREAD

**Issue by flespark** [fangbinwei/aliyun-oss-website-action#5]
current directory: /github/workspace
endpoint: oss-cn-hangzhou.aliyuncs.com
bucketName: webpage-hz
folder: public
exclude: []
indexPage: index.html
notFoundPage: 404.html
isCname: false
skipSetting: true
HTMLCacheControl: no-cache
imageCacheControl: max-age=864000
otherCacheControl: max-age=2592000
skip setting static pages related configuration
---- delete start ----
occurred error: oss: service returned error: StatusCode=400, ErrorCode=InvalidArgument, ErrorMessage="Authorization header is invalid.", RequestId=60A4BCF86E537B39375FE2E7

[400错误](https://help.aliyun.com/document_detail/185228.html?spm=a2c4g.11186623.6.1850.3666295fKNHFqE)

重复检查了配置没有问题，是阿里云的SDK有修改吗

**Comment by fangbinwei** [comment]
accessKeyId, accessKeySecret 正确配置了嘛

![image](https://user-images.githubusercontent.com/13298807/118779260-73704780-b8bd-11eb-8ee2-630b0730ca7c.png)

**Comment by flespark** [comment]
配置了，不过我的显示的是在Environment secrets。看来我搞错了，orz

**Comment by flespark** [comment]
可以工作了，感谢指导:heart:

**Comment by fangbinwei** [comment]
嗯嗯  以前github action没有environment secrets,  看了下要使用这个似乎需要 指定一下enviorment, 

```diff
jobs:  
  upload:
    runs-on: ubuntu-latest
+    environment: environment-name

```

> https://stackoverflow.com/questions/66521958/how-to-access-environment-secrets-from-a-github-workflow
