### ISSUE TITLE
是否提供不清空bucket的上传选项

### ISSUE THREAD

**Issue by jerryliang64** [fangbinwei/aliyun-oss-website-action#7]
当前这个Actions触发后会清空原有的bucket，不知道是否可以设置不清空bucket

**Comment by yes8080** [comment]
建议给清空bucket增加一个排除项，同时该排除项也不再上传oss，提升效率，我看日志，其余动作都在900毫秒以内，唯有上传这一步耗时5秒左右，有些内容是不必删除后再上传的

**Comment by fangbinwei** [comment]
感谢反馈，我觉得可以有两个优化，近期计划加上
1.是否清空bucket 可配置
2.只上传内容变化的文件

or 一步到位，先上传内容变化的文件，清除其余多余文件

**Comment by yes8080** [comment]
> 谢谢反馈，我可以有两个最快的计划，近期可以 配置 1.是否清桶 2. 只上传内容变化的文件
> 
> 或前一步，先上传内容变化的文件，清除其余剩余文件

实现上可以参考一下  https://github.com/marketplace/actions/ali-oss-website-action  
> incremental: true # 开启增量上传，只上传 md5 值变化、新增、删除 的文件

**Comment by fangbinwei** [comment]
😋 已经发布了v1.3.0 默认使用了增量上传

可以使用 `uses: fangbinwei/aliyun-oss-website-action@v1.3.0`
如果使用的`uses: fangbinwei/aliyun-oss-website-action@v1`, 那下次跑action的时候, 就会使用新功能了

![image](https://user-images.githubusercontent.com/13298807/165602239-ddbce7ec-ee81-4b49-a9ed-0ba14e0df72c.png)

> https://github.com/fangbinwei/aliyun-oss-website-action/tree/master#incremental
